---

- name: "Install requirements packages"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-openssl

- name: "Install requirements pip packages"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - boto3

- name: "Copy Cycloid checks"
  copy:
    src: "{{ item }}"
    dest: /usr/bin/
    owner: root
    group: root
    mode: u+rxw,g+rx,o+rx
  with_items:
    - check_lb_certs.py
    - check_ses.py
