---
- include_role:
    name: dj-wasabi.telegraf
  vars:
    # Because of ansible but we can't use same var name, so adding cycloid_ prefix
    telegraf_agent_output: "{{ cycloid_telegraf_agent_output }}"
    telegraf_agent_logfile: "{{ cycloid_telegraf_agent_logfile }}"
    telegraf_agent_interval: "{{ cycloid_telegraf_agent_interval }}"
    telegraf_agent_flush_interval: "{{ cycloid_telegraf_agent_flush_interval }}"
    telegraf_plugins_default: "{{ cycloid_telegraf_plugins_default }}"
    telegraf_agent_version: "{{cycloid_telegraf_agent_version}}"
    telegraf_agent_package_state: "{{ cycloid_telegraf_agent_package_state }}"

- include_tasks: extra_checks.yml
  when: telegraf_extra_checks

- include_tasks: aws_checks.yml
  when: telegraf_aws_checks
